code --install-extension apollographql.vscode-apollo
code --install-extension blzjns.vscode-raml
code --install-extension brenosolutions.sqlformatter
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension mikestead.dotenv
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension naumovs.color-highlight
code --install-extension PascalReitermann93.vscode-yaml-sort